### ISSUE TITLE
向 Document 1 中的例程发送 ping，机器人会回复两次 pong

### ISSUE THREAD

**Issue by RisingInIris2017** [Box-s-ville/luciabot#5]
## 问题描述
我按照 [Document 1](https://github.com/Box-s-ville/luciabot/blob/v1/guide/New%20Text%20Document.md) 中的说明编写了带有 `ping.py` 插件的机器人，启动机器人和 go-cqhttp 后，机器人能正常接受上报数据，也能正常接收命令，但发送一次 `ping` 命令，机器人会响应两次 `pong!`。
## 系统环境
我在 IDLE 中运行下列命令：
```
>>> print(sys.version_info)
sys.version_info(major=3, minor=9, micro=0, releaselevel='final', serial=0)
```
可知 Python 版本 3.9.0
## GO-CQHTTP版本
v1.0.0-beta3
## 问题代码
https://github.com/RisingInIris2017/MARYTBot/tree/main/MarytBOT
所有的代码按照其文件结构在上面这个仓库中展示。

由于能力所限，我不能找到问题的原因，所以编写此 Issue，希望能得到您的帮助。
在此事先感谢您耐心阅读我的问题，谢谢！

**Comment by cleoold** [comment]
Try again now. Does it still happen?

**Comment by RisingInIris2017** [comment]
> Try again now. Does it still happen?

Yes. Bot will reply "pong!" twice, both in private messages and in QQ group.

**Comment by RisingInIris2017** [comment]
Thanks for helps from everyone who have commented here.
I have found the cause of the problem: I wrote my go-cqhttp bot's config.yml like this
```yaml
servers:
  - http:
      disabled: false
      host: 127.0.0.1
      port: 5700
      post:
        - url: '127.0.0.1:5701/post'
        - url: '127.0.0.1:5702'

  - ws-reverse:
      disabled: false
      universal: ws://127.0.0.1:5702/ws
```
So the bot have problem on posting messages to port 5702, which is listened by my bot.
Then bot reply "pong!" twice.

The example program in Document 1 is correct. 
Thanks you kind-hearted guys again!
